version: '3.8'

services:
  # PHP Application Service
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel_ilkom_compro
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      # Use volumes to persist installed packages and built assets
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - /var/www/html/public/build
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
    driver: local
